import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

export type PdfPayload = {
  prenom: string;
  nomAncestral: string;
  archetypeId: string;
  texteParchemin: string;
  numeroCollection: number;
  langue: "fr" | "en";
};

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: "Times-Roman",
    fontSize: 12,
    lineHeight: 1.6,
    color: "#1A1A2E",
  },
  parcheminPage: {
    padding: 50,
    backgroundColor: "#FEFCF0",
  },
  certificatPage: {
    padding: 50,
    backgroundColor: "#FFFFFF",
  },
  title: {
    fontFamily: "Times-Roman",
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 30,
    color: "#C9A84C",
  },
  subtitle: {
    fontSize: 14,
    textAlign: "center",
    marginBottom: 20,
    fontStyle: "italic",
  },
  body: {
    fontSize: 12,
    lineHeight: 1.8,
    textAlign: "justify",
  },
  signature: {
    marginTop: 40,
    textAlign: "right",
    fontStyle: "italic",
  },
  divider: {
    borderBottom: "1 solid #C9A84C",
    marginVertical: 20,
    opacity: 0.4,
  },
  numeroSerie: {
    fontSize: 10,
    textAlign: "center",
    color: "#888",
    marginTop: 40,
  },
  label: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#C9A84C",
  },
  value: {
    fontSize: 12,
    marginBottom: 12,
  },
  certBorder: {
    border: "2 solid #C9A84C",
    padding: 30,
    marginTop: 20,
  },
  sealPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    border: "2 solid #C9A84C",
    alignSelf: "center",
    marginVertical: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
});

function ParcheminDocument({ payload }: { payload: PdfPayload }) {
  return (
    <Document>
      <Page size="A4" style={styles.parcheminPage}>
        <Text style={styles.title}>✦ TOTEM ANCESTRAL ✦</Text>
        <Text style={styles.subtitle}>Le Parchemin Narratif</Text>
        <View style={styles.divider} />
        <Text style={styles.label}>Destinataire</Text>
        <Text style={styles.value}>{payload.prenom}</Text>
        <Text style={styles.label}>Nom Ancestral</Text>
        <Text style={styles.value}>{payload.nomAncestral}</Text>
        <Text style={styles.label}>Collection</Text>
        <Text style={styles.value}>Tome {payload.numeroCollection}</Text>
        <View style={styles.divider} />
        <Text style={styles.body}>{payload.texteParchemin}</Text>
        <View style={styles.divider} />
        <Text style={styles.signature}>✦ SENYCE PARTNERS ✦</Text>
        <Text style={styles.numeroSerie}>
          Certifié authentique — {payload.nomAncestral} — N°
          {String(payload.numeroCollection).padStart(6, "0")}
        </Text>
      </Page>
    </Document>
  );
}

function CertificatDocument({ payload }: { payload: PdfPayload }) {
  const localeText =
    payload.langue === "fr"
      ? {
          title: "CERTIFICAT D'AUTHENTICITÉ",
          subtitle: "Œuvre d'art numérique générée par intelligence artificielle",
          body: `Nous, SENYCE PARTNERS, certifions que l'œuvre intitulée "${payload.nomAncestral}" a été créée exclusivement pour ${payload.prenom} à l'aide de notre pipeline d'intelligence artificielle Totem Ancestral.`,
          detail: `Cette œuvre unique, numérotée et signée, est le fruit des réponses personnelles fournies par le destinataire lors de son parcours initiatique. Elle intègre des éléments narratifs, visuels et sonores générés sur mesure.`,
          date: `Fait à距离 du monde, le ${new Date().toLocaleDateString("fr-FR")}`,
          signature: "Pour SENYCE PARTNERS",
        }
      : {
          title: "CERTIFICATE OF AUTHENTICITY",
          subtitle: "Digital artwork generated by artificial intelligence",
          body: `We, SENYCE PARTNERS, certify that the artwork titled "${payload.nomAncestral}" was created exclusively for ${payload.prenom} using our Totem Ancestral artificial intelligence pipeline.`,
          detail: `This unique, numbered and signed work is the fruit of the personal responses provided by the recipient during their initiatory journey. It integrates custom-generated narrative, visual and audio elements.`,
          date: `Done on ${new Date().toLocaleDateString("en-US")}`,
          signature: "For SENYCE PARTNERS",
        };

  return (
    <Document>
      <Page size="A4" style={styles.certificatPage}>
        <View style={styles.certBorder}>
          <Text style={styles.title}>✦ {localeText.title} ✦</Text>
          <Text style={styles.subtitle}>{localeText.subtitle}</Text>
          <View style={styles.divider} />
          <View style={styles.sealPlaceholder}>
            <Text style={{ fontSize: 8, color: "#C9A84C", textAlign: "center" }}>SCEAU</Text>
          </View>
          <Text style={styles.body}>{localeText.body}</Text>
          <Text style={{ ...styles.body, marginTop: 12 }}>{localeText.detail}</Text>
          <View style={styles.divider} />
          <Text style={styles.label}>Œuvre</Text>
          <Text style={styles.value}>{payload.nomAncestral}</Text>
          <Text style={styles.label}>Numéro de série</Text>
          <Text style={styles.value}>{String(payload.numeroCollection).padStart(6, "0")}</Text>
          <Text style={styles.label}>Propriétaire</Text>
          <Text style={styles.value}>{payload.prenom}</Text>
          <Text style={styles.label}>{payload.langue === "fr" ? "Date" : "Date"}</Text>
          <Text style={styles.value}>{localeText.date}</Text>
          <View style={styles.divider} />
          <Text style={styles.signature}>{localeText.signature}</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generatePDFs(payload: PdfPayload): Promise<{
  parcheminBuffer: Buffer;
  certificatBuffer: Buffer;
}> {
  const [parcheminBuffer, certificatBuffer] = await Promise.all([
    renderToBuffer(<ParcheminDocument payload={payload} />),
    renderToBuffer(<CertificatDocument payload={payload} />),
  ]);

  return { parcheminBuffer, certificatBuffer };
}
